### ISSUE TITLE
Blocking issue: waiting on timed promises

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/jquery-2-typescript-async-await-adapter#1]
https://rawgit.com/JoshuaKGoldberg/jquery-2-typescript-async-await-adapter/c5967e1ac4250f97bd7dabbed65a2683e8dbdb42/test/index.html

```
waits on timed promises ‣
AssertionError: expected undefined to equal 'value'
    at tests.js:165:43
    ...
```

`__generator` is immediately running the next step without a real next value. I don't understand why. Filed https://github.com/Microsoft/TypeScript/issues/14689 to see if there's a more-comprehensible version available.

**Comment by AdamTReineke** [comment]
ICYMI: They pointed you to this documentation: https://github.com/Microsoft/tslib/blob/6be26c8c0772d9931c7c4a0b981160e164782e53/docs/generator.md

**Comment by JoshuaKGoldberg** [comment]
Thanks :) I forgot to close this issue. Blocking promises work!... At the cost of complex async catching. 

My next steps will be to make a repo with a fully documented version of the generator.
